# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1704.01"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "public_network", ip: "10.1.0.26", netmask: "255.255.255.0", gateway: "10.1.0.1"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = true
    ansible.groups = {
        'local' => ['default']
    }
    ansible.playbook = "playbook.yml"
  end
end
